on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - run: poetry run flake8
